const { supabaseAdmin } = require('../config/database');
const archiver = require('archiver');

/**
 * 내 앱 목록 조회
 */
exports.getMyApps = async (req, res, next) => {
  try {
    const userId = req.user.id;

    const { data, error } = await supabaseAdmin
      .from('generated_apps')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) throw error;

    res.json({
      success: true,
      apps: data,
      count: data.length
    });
  } catch (error) {
    next(error);
  }
};

/**
 * 앱 상세 조회
 */
exports.getAppById = async (req, res, next) => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    const { data, error } = await supabaseAdmin
      .from('generated_apps')
      .select('*')
      .eq('id', id)
      .eq('user_id', userId)
      .single();

    if (error || !data) {
      return res.status(404).json({
        success: false,
        error: '앱을 찾을 수 없습니다.'
      });
    }

    res.json({
      success: true,
      app: data
    });
  } catch (error) {
    next(error);
  }
};

/**
 * 앱 삭제
 */
exports.deleteApp = async (req, res, next) => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    const { error } = await supabaseAdmin
      .from('generated_apps')
      .delete()
      .eq('id', id)
      .eq('user_id', userId);

    if (error) throw error;

    res.json({
      success: true,
      message: '앱이 삭제되었습니다.'
    });
  } catch (error) {
    next(error);
  }
};

/**
 * 앱 ZIP 다운로드
 */
exports.downloadApp = async (req, res, next) => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    // 앱 조회
    const { data: app, error } = await supabaseAdmin
      .from('generated_apps')
      .select('*')
      .eq('id', id)
      .eq('user_id', userId)
      .single();

    if (error || !app) {
      return res.status(404).json({
        success: false,
        error: '앱을 찾을 수 없습니다.'
      });
    }

    // 파일명에서 특수문자 제거
    const safeName = (app.title || 'app').replace(/[^a-zA-Z0-9가-힣]/g, '_');

    // ZIP 헤더 설정
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${encodeURIComponent(safeName)}.zip"`);

    // ZIP 아카이브 생성
    const archive = archiver('zip', { zlib: { level: 9 } });

    // 에러 핸들링
    archive.on('error', (err) => {
      throw err;
    });

    // 응답 스트림에 연결
    archive.pipe(res);

    // index.html 생성 (통합 파일)
    const indexHtml = `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${app.title || 'Mini App'}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
${app.html_code || ''}
<script src="script.js"></script>
</body>
</html>`;

    // 파일 추가
    archive.append(indexHtml, { name: 'index.html' });
    archive.append(app.css_code || '/* No CSS */', { name: 'style.css' });
    archive.append(app.js_code || '// No JavaScript', { name: 'script.js' });

    // README 추가
    const readme = `# ${app.title || 'Mini App'}

${app.description || ''}

## 생성 정보
- 생성일: ${new Date(app.created_at).toLocaleDateString('ko-KR')}
- 품질 점수: ${app.quality_score || 'N/A'}점
- 앱 타입: ${app.app_type || 'custom'}

## 사용 방법
index.html 파일을 브라우저로 열어서 실행하세요.

---
Generated by Mini App Generator
`;
    archive.append(readme, { name: 'README.md' });

    // 아카이브 완료
    await archive.finalize();

  } catch (error) {
    next(error);
  }
};

/**
 * 버전 히스토리 조회 (Phase 3)
 */
exports.getVersionHistory = async (req, res, next) => {
  try {
    // Phase 3에서 구현
    res.status(501).json({
      success: false,
      error: '이 기능은 아직 구현되지 않았습니다.'
    });
  } catch (error) {
    next(error);
  }
};

/**
 * 특정 버전으로 롤백 (Phase 3)
 */
exports.rollbackVersion = async (req, res, next) => {
  try {
    // Phase 3에서 구현
    res.status(501).json({
      success: false,
      error: '이 기능은 아직 구현되지 않았습니다.'
    });
  } catch (error) {
    next(error);
  }
};
